services:
  db:
    image: postgres:15
    container_name: django_db
    env_file:
      - ./.env.prod.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: django_web
    environment:
      - DJANGO_DEBUG=0
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - SQL_ENGINE=${SQL_ENGINE}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_HOST=${SQL_HOST}
      - SQL_PORT=${SQL_PORT}
      - DATABASE=postgres
    env_file:
      - ./.env.prod
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    container_name: django_nginx
    ports:
      - "1337:80"
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - ./nginx/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
